**【問題1】行列積を手計算する**  
AとBの行列積を手計算で解いてください。  
計算過程もマークダウンテキストを用いて説明してください。  
$% <![CDATA[
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right] %]]>$

手計算  
$% <![CDATA[
AB = \left[
\begin{array}{ccc}
  -1*0 +    2*0 +    3*2 &  -1*2 +    2*2 +    3*9 & -1*1    +    2*(-8) +    3*(-1)\\
   4*0 + (-5)*0 +    6*2 &   4*2 + (-5)*2 +    6*9 &  4*1    + (-5)*(-8) +    6*(-1)\\
   7*0 +    8*0 + (-9)*2 &   7*2 +    8*2 + (-9)*9 &  7*1    +    8*(-8) + (-9)*(-1)
\end{array}
\right]
= \left[
\begin{array}{ccc}
     6 &  29 & -20\\
    12 &  52 &  38\\
   -18 & -51 & -48
\end{array}
\right] %]]>$

**【問題2】NumPyの関数による計算**  
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。  
これらを使い行列積を計算してください。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.dot(a_ndarray, b_ndarray)
ab_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

**【問題3】ある要素の計算を実装**  
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。  
行列Aの(0,0)の要素$a_{0, 0}$と行列Bの(0,0)の要素$b_{0, 0}$  
行列Aの(0,1)の要素$a_{0, 1}$と行列Bの(1,0)の要素$b_{1, 0}$  
行列Aの(0,2)の要素$a_{0, 2}$と行列Bの(2,0)の要素$b_{2, 0}$  
それらの値を全て足し合わせる
数式で表すと  

$\sum^{2}_{k=0}a_{0,k}b_{k,0}$

です。  
この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

<!-- **【問題4】行列積を行う関数の作成**   -->
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。  
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。  
計算結果である$3 \times 3$の行列Cの各要素$c_{i, j}$は数式で表すと次のようになります。  

$c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。  
インデックス$i$や$j$を1増やすと、次の行や列に移ることができます。

In [2]:
def calc_2matrix_product(ndarray1, ndarray2):
    ab = []
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[1]):
            ab.append(sum(a_ndarray[i, :] * b_ndarray[:, j]))
    calculated_ndarray = np.array(ab).reshape(a_ndarray.shape[0], b_ndarray.shape[1])
    return calculated_ndarray

ab_ndarray = calc_2matrix_product(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**【問題5】計算が定義されない入力を判定する**  
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。  
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [3]:
def calc_2matrix_product(ndarray1, ndarray2):
    if ndarray1.shape[1] == ndarray2.shape[0]:
        ab = []
        for i in range(a_ndarray.shape[0]):
            for j in range(b_ndarray.shape[1]):
                ab.append(sum(a_ndarray[i, :] * b_ndarray[:, j]))
        calculated_ndarray = np.array(ab).reshape(a_ndarray.shape[0], b_ndarray.shape[1])
        return calculated_ndarray
    else:
        print("引数1の行数と引数2の列数の数が一致していません。")

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
calculated_ndarray = calc_2matrix_product(d_ndarray, e_ndarray)
print(calculated_ndarray)

引数1の行数と引数2の列数の数が一致していません。
None


**【問題6】転置**  
片方の行列を転置することで、行列積が計算できるようになります。  
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [4]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print("e_ndarray = \n", e_ndarray)
transposed_e_ndarray = e_ndarray.T
print("transposed_e_ndarray = \n", transposed_e_ndarray)

calculated_ndarray = calc_2matrix_product(d_ndarray, transposed_e_ndarray)
print("calculated_ndarray = \n", calculated_ndarray)

e_ndarray = 
 [[-9  8  7]
 [ 6 -5  4]]
transposed_e_ndarray = 
 [[-9  6]
 [ 8 -5]
 [ 7  4]]
calculated_ndarray = 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
