# 【問題1】これまで利用してきたクラスの列挙

クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。  
この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。  
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。  

- pandas  
pandas.DataFrame  
pandas.read_csv  


- matplotlib  
matplotlib.figure


- scikit-learn
sklearn.preprocessing
sklearn.metrics

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。  
最低でもそれぞれ5つ以上答えてください。  

- メソッド  
numpy.sum()  
numpy.mean()  
numpy.var()  
numpy.reshape()  
numpy.arange()

- インスタンス  
shape  
ndim  
size  
itemsize  
flags

# 【問題3】標準化クラスをスクラッチで作成

理解をより深めるため、StandardScalerをスクラッチで作成しましょう。  
scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。  

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。  

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。  

今回のスクラッチではcopy、with_mean、with_stdなどのパラメータを省略しましたが、このようにインスタンス化の際にパラメータを指定して保存しておくということはよくある使い方です。  

コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、 特殊メソッド と呼びます。

In [19]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
    
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = X / self.mean_
        return X_scaled

In [26]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[1.04938272 1.05740181 0.96551724 0.90909091]
 [1.00823045 0.90634441 0.96551724 0.90909091]
 [0.96707819 0.96676737 0.89655172 0.90909091]
 [0.94650206 0.93655589 1.03448276 0.90909091]
 [1.02880658 1.08761329 0.96551724 0.90909091]
 [1.11111111 1.17824773 1.17241379 1.81818182]
 [0.94650206 1.02719033 0.96551724 1.36363636]
 [1.02880658 1.02719033 1.03448276 0.90909091]
 [0.90534979 0.87613293 0.96551724 0.90909091]
 [1.00823045 0.93655589 1.03448276 0.45454545]]


# 【問題4】 四則演算を行うクラスの作成

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。  

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。  

クラス名や説明文も適切に書き換えてください。

In [47]:
class CalculateClass():
    """
    初期値に対して、足し算、引き算、掛け算、割り算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        if (type(value)==int) or (type(value)==float):
            print("初期値{}が設定されました".format(self.value))
        else:
            print("設定した初期値は数値ではありません")
    
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
    
    def pro(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value2
    
    def div(self, value2):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value2

In [48]:
example1 = CalculateClass(5)
example1.add(5)
print("value : {}".format(example1.value))

example2 = CalculateClass(5)
example2.sub(5)
print("value : {}".format(example2.value))

example3 = CalculateClass(5)
example3.pro(5)
print("value : {}".format(example3.value))

example4 = CalculateClass(5)
example4.div(5)
print("value : {}".format(example4.value))

example5 = CalculateClass("1")

初期値5が設定されました
value : 10
初期値5が設定されました
value : 0
初期値5が設定されました
value : 25
初期値5が設定されました
value : 1.0
設定した初期値は数値ではありません
